### ISSUE TITLE
Should :require support checking combinations of required keys?

### ISSUE THREAD

**Issue by borkdude** [babashka/cli#33]
E.g.: both `:git/sha` and `:git/url` or `:mvn/version` must be provided.

``` clojure
:require #{[:git/sha :git/url] [:mvn/version]}
```

What if you have one common required key? Add them to each entry?

``` clojure
:require #{[:lib :git/sha :git/url] [:lib :mvn/version]}
```

or support nesting?

``` clojure
:require [:lib #{[:git/sha :git/url] [:mvn/version]}]
```

**Comment by rads** [comment]
@borkdude: This issue slipped by me last week, just catching up now. In general I'm in favor of making the CLI arg parsing more explicit. That said, I'm pretty inexperienced right now with `babashka.cli`, so I need some time to learn and think about what makes the most sense outside of just the `neil new` use case.

**Comment by borkdude** [comment]
Let's let this issue have some hammock time for a while.

**Comment by rads** [comment]
Rather than adding more features to `:require`, what do you think about extending `:validate` to support predicates _across_ options, rather than one predicate per option?
```clojure
(require '[babashka.cli :as cli]
         '[babashka.neil.new :as new])

(defn valid-combinations? [cli-opts]
  (contains? new/valid-lib-opts (new/deps-new-cli-opts->lib-opts cli-opts)))

(cli/parse-args ["--local/root" "--latest-sha"]
                {:validate {::cli/opts valid-combinations?}})
```
Rationale:
- We would only need to add `::cli/opts` once and then many different use cases could be supported beyond checking for valid combinations of keys.
- I think babashka.cli should focus primarily on parsing CLI strings into a standard data format and not try to add more advanced parsing features in the API.
- Once the CLI args are available as Clojure data, I'd prefer to do more advanced parsing of `opts` with a dedicated library such as clojure.spec or Malli.
- Even if not using a separate lib for parsing (such as with `neil`), I think it's cleaner to be decoupled from babashka.cli using generic predicate functions.

**Comment by rads** [comment]
I should note that the only thing required to get the above example working is support for the `::cli/opts` key. The `valid-combinations?` code already works fine since I'm reusing existing functions from the `babashka.neil.new` namespace.

**Comment by borkdude** [comment]
I agree that it's already very easy to validate the data yourself after parsing. I don't think we'd need to add `::cli/opts` for that either then right?

**Comment by borkdude** [comment]
I'll close this until further notice.

**Comment by rads** [comment]
> I agree that it's already very easy to validate the data yourself after parsing. I don't think we'd need to add ::cli/opts for that either then right?

Yeah, it's not strictly needed, so I'm fine leaving things as they are.

**Comment by rads** [comment]
To clarify, I think we should prefer functions that work standalone with `bb -x`, so really they are just regular Clojure functions that take a map. The more we rely on behavior in babashka.cli outside of what `bb -x` does by default, the more we are coupling our functions to the CLI.

In contrast, if our CLI is just a wrapper around Clojure functions, we can use standard function composition to create new CLIs on top of lower-level CLIs. This is without having to result to helpers like `babashka.task/exec` just to call the functions at each level.
